#!/bin/sh

authorization_key=changeme

if test "$HTTP_AUTHORIZATION" = "$authorization_key"
then
	cat > info.json
	printf "Status: 200 OK\r\n\r\n"
else
	cat > /dev/null
	printf "Status: 401 Unauthorized\r\n\r\n"
fi
